### PR TITLE
Merge upstream 3.0.1 into Feature/websocket reborn

### LINKED ISSUE #37: Merge upstream 2.28.0 into websocket-reborn + Signal update
Folks,

Again still too busy to do this right now, but upstream has had a major update. If someone wants to step in again to do the merge from upstream, go for it otherwise in a few weeks I will finally get back to it.

If someone does step in to do the merge, BE CAREFUL, MANUALLY TEST THE NEW CODE WORKS - there's gonna be a huge diff and stuff will probably break because of it.

### PR DESCRIPTION
**Pull request by relyt29**
Notes:

I have this working, tested in the usual way. 
# SIGNAL PHONE CALLS SHOULD AND OUGHT NOT TO WORK!!
#### texting messaging via data channel does work

I disabled redphone server registration. If someone else wants to work on figuring out how to make redphone registration work when you don't have a gcmId to give the redphone server, be my guest. My priority is making sure texting still works and that the codebase doesn't fall so far behind upstream that its no longer maintainable. Check out `src/org/thoughtcrime/securesms/service/RegistrationService.java` that's probably where you'll want to start.

adb-screenshot-2015-10-03-20-10-42-917055555

Closes #37 

If this is merged I think it will make sense to make a separate issue tracking progress getting redphone to work without GCM

### CODE REVIEW

**Comment by xmikos** [comment]
Could you make it that way, that everything (even RedPhone server registration) still works if you have GCM and WebSocket is only used on devices without Google Play Services? That way we wouldn't need to maintain two separate builds and can have universal builds useful for both people with/without Google Play Services. But it would need option to force WebSocket in preferences (even if one have GCM on the phone).

**Comment by onny** [comment]
@xmikos: Good point! Such a hack would be useful!
Thank you f41c0r for the work. Hope this gets merged soon!

**Comment by relyt29** [comment]
@xmikos That should be doable, I'm too busy atm, but perhaps next weekend.

**Comment by zebra-ok** [comment]
Btw @f41c0r, Signal phone calls do work, only registration is stripped from the code. That means, if you are already registered with your phone number through legacy RedPhone app, I successfully called other Signal users. 
RedPhone allowed registration and call initiation without GCM, but it was not possible to receive calls (same here now).

**Comment by thrillfall** [comment]
@art1fa Do you mean that if i registered via PhoneLibre i should be able to make calls from the LibreSignal (websocket version) app? I ask because that does not work in my case (no gapps installed).

**Comment by dev-mb-zz** [comment]
@thrillfall Calling to "Appstore Signal-users" works for me with the websocket Signal from f-droid.
I didn't register for Redphone just for normal Textsecure.

**Comment by xmikos** [comment]
@thrillfall From what I have tried, it seems that it will work if you have previously registered with RedPhone/Signal server with GCM. Then you can make calls even from websocket-fork, but receiving calls will still not work.

**Pull request merged**
