### PR TITLE
Add registration warning popup

### PR DESCRIPTION
**Pull request by JavaJens**
This pull requests adds to #24 in that is shows the warning to all users that have an issue with their GCM setup.

This way no user is left behind.

### CODE REVIEW

**Comment by relyt29** [comment]
Okay. I just tested it, it works fine. Screenshot attached for proof if you don't believe me:
adb-screenshot-2015-08-12-10-52-52-698006296

So at this point, this pull request comes down to a philosophical issue and not an issue with code. This is your repo and if you want to support everybody, I'm fine with it. The code looks good and I tested it, it's ready to merge. But let me talk for a moment about philosophy:

At the end of the day, when we make a PR to upstream, @moxie0 will have to decide who Open Whisper Systems wants to support and what level of support he wants to provide to those people with regards to no gApps users.

When I started/wanted to dev on this stuff to get websockets working, my primary concern was bing able to support my personal device which doesn't have gApps/GCF/proprietary userland code on it. People who are using your repo have to have at least a base level of technical experience in order to figure out how to compile the code, etc. So the reason I proposed adding the popup warning for WS users was that I envisioned that if you were using the websockets only branch, you had compiled it yourself, and were well aware that you were entering a land of potentially buggy software and no official support. I wanted to formalize that. People using the websocket fork should know that they are not officially supported and should know not to add to the support burden of the official developers, who have enough stress on their hands trying to support the huge nontechnical audience that uses TS. (instead those people should be harassing us so we can fix the bugs before we merge back into upstream [in the event that someday that will actually happen and we will get merged upstream :persevere: :sob: ])

If @moxie0 can spare the time to weigh in on what he thinks and what is most likely to get merged that would be helpful for us to move this PR forward in a way that would be helpful for merging upstream but he's also busy AF and probably has support fatigue from trying to keep issues on the tracker in a reasonable state. Based on his remarks I have read elsewhere, I'm guessing he'd rather focus on providing excellent support for Google Play users, if at the cost of merging websockets-only code is a new support burden. He may say "Thanks, but we're not going to do this" and refuse to officially support websocket-only code altogether in any capacity.

But as this PR is currently, this will allow everybody who has any problem whatsoever with their GCM to use TS, as long as they click through the "unsupported" dialog. That means that if Moxie, at a later date, merges this particular change, and then some user down the road manages to get an apk of the upstream code, either through Google play or some other means, and they have a broken GCM, _they will still see the popup and be allowed to register even if WS-only is not turned on,_ if they actually have some legitimate problem with GCM but have a partially working configuration of come kind.

Something to think about, who we/OWS wants to support. I can see both sides of the coin and don't feel strongly one way or another, but, it's something to think about before merging. I tested the code it's functional, I think its ready for merge **if** this is how you want to do it.

**Comment by JavaJens** [comment]
Mhh, I haven't considered this side of the medallion. If I understand you correctly, you plan to only enable websocket support if specifically configured during build time?

**Comment by relyt29** [comment]
Well, that's the current status quo. We could potentially set it as a preferences option... but adding those is not something moxie likes to do

**Comment by relyt29** [comment]
Have you made a decision on what you want to do here?

**Pull request closed without merging**
