### PR TITLE
Update to v3.12.0

### PR DESCRIPTION
**Pull request by mimi89999**
@JavaJens Could you help me test this update? All of my contacts are busy.

### CODE REVIEW

**Comment by JavaJens** [comment]
Will do now.

**Comment by JavaJens** [comment]
Looks good! Thx!

**Comment by otr2015** [comment]
@javajens @xmikos could you please update the f-droid repository with the new version? Thanks

**Comment by JavaJens** [comment]
@otr2015 I don't run this repository.

**Pull request merged**
