### PR TITLE
Merge upstream v3.6.1

### PR DESCRIPTION
**Pull request by schachmat**
works with the 1.8.2 version of libtextsecure-java, which I also made a PR for.

### CODE REVIEW

**Comment by xmikos** [comment]
Please can you merge it? I think this update is needed for complete multi-device support (see newly released beta of [Signal Desktop](https://whispersystems.org/blog/signal-desktop/) client).

**Comment by schachmat** [comment]
I can confirm, that the device linking necessary for Signal Desktop works with this version 3.6.1. I already tested it yesterday evening with a few friends.

**Comment by JavaJens** [comment]
I haven't managed to test this yet, but will merge and if there is a problem, just report it.

**Comment by openpaul** [comment]
works, but is slower. Somehow there are more animations now?

**Pull request merged**
