### PR TITLE
Update from upstream to 2.23

### PR DESCRIPTION
**Pull request by relyt29**
Pulling in upstream in order to stay current. Thankfully this automagically merged via git with no conflicts. Have tested sending and receiving messages on the staging server.
screen

### CODE REVIEW

**Comment by relyt29** [comment]
I should mention - I tested on replicant, the websocket fork, without google play services installed, sending to a normal client with google play installed, upstream automation build.

**Comment by dev-mb-zz** [comment]
Just compiled and tested it on a Cyanogenmod 12.1 over Wifi and 3G without Gapps in combination with another device which has Gapps and the Playstore version installed. Seems to work normal over Wifi and 3G.
Great work to all who made it possible. Thanks  a lot.

**Comment by relyt29** [comment]
On my GApps phone (vanilla upstream), you can refresh the push directory by swiping down in NewConversationActivity but on replicant (this PR) this does not seem to work.

Edit: see commit f2a323ef7f0513cdad8516af736e56781e06c085 ([conversation here](https://github.com/WhisperSystems/TextSecure/commit/f2a323ef7f0513cdad8516af736e56781e06c085))

Edit Edit: I may just keep [my own separate branch](https://github.com/f41c0r/TextSecure/tree/feature/websocket-reborn-replicant) that mirrors upstream but doesn't block the push directory refresh as it's highly annoying to not be able to refresh when you add new contacts

Edit^3: (if on an older device): System Settings -> Accounts -> TextSecure -> Contacts (Touch to sync now)

**Comment by f41c0r** [comment]
commit f2a323ef7f0513cdad8516af736e56781e06c085

**Comment by f41c0r** [comment]
Hmm. Not sure what a good approach to take here is. I guess I may just keep my own separate branch that mirrors upstream but doesn't block the push directory refresh as it's highly annoying

**Pull request merged**
