### PR TITLE
Update to v3.9.0

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by Diapolo** [comment]
How is the update process defined here? I'd love to test the GCM-less version, but I want to be sure that I'm able to use a current version based on current master ;).

**Comment by JavaJens** [comment]
There is no update process :smile:
Right now we try to keep up with releases of upstream. Whenever somebody finds the time to submit a PR I merge it.

**Comment by Diapolo** [comment]
@JavaJens But at least you can verify that the stuff you merge here doesn't break websocket support (e.g. merge conflict and a manual checkup by you?) or doesn't contain bad/mallicous commits that don't come from upstream repo?

**Comment by Diapolo** [comment]
You coul also just rebase your repo with the current master, wouldn't that be easier?

**Comment by relyt29** [comment]
I used to try to show screenshots as proof that I tested it adequately, we should probably have a more formalized process for getting in commits...

**Comment by Diapolo** [comment]
I'd love to see a more verifyable process here, then I'd be willing to help testing. Sadly I'm no Java developer, I only have rudimentary C/C++ skills.

**Pull request merged**
